-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;
package eecs361_gates is

  component not_gate
    port (
      x : in std_logic;
      z : out std_logic
    );
  end component not_gate;

  component not_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component not_gate_n;

  component not_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component not_gate_32;

  component and_gate
    port (
      x : in std_logic;
      y : in std_logic;
      z : out std_logic
    );
  end component and_gate;

  component and_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      y : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component and_gate_n;

  component and_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      y : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component and_gate_32;

  component or_gate
    port (
      x : in std_logic;
      y : in std_logic;
      z : out std_logic
    );
  end component or_gate;

  component or_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      y : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component or_gate_n;

  component or_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      y : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component or_gate_32;

  component nand_gate
    port (
      x : in std_logic;
      y : in std_logic;
      z : out std_logic
    );
  end component nand_gate;

  component nand_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      y : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component nand_gate_n;

  component nand_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      y : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component nand_gate_32;

  component nor_gate
    port (
      x : in std_logic;
      y : in std_logic;
      z : out std_logic
    );
  end component nor_gate;

  component nor_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      y : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component nor_gate_n;

  component nor_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      y : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component nor_gate_32;

  component xor_gate
    port (
      x : in std_logic;
      y : in std_logic;
      z : out std_logic
    );
  end component xor_gate;

  component xor_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      y : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component xor_gate_n;

  component xor_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      y : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component xor_gate_32;

  component xnor_gate
    port (
      x : in std_logic;
      y : in std_logic;
      z : out std_logic
    );
  end component xnor_gate;

  component xnor_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      y : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component xnor_gate_n;

  component xnor_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      y : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component xnor_gate_32;
end;
