-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;

entity not_gate_32 is
  port (
    x   : in  std_logic_vector(31 downto 0);
    z   : out std_logic_vector(31 downto 0)
  );
end not_gate_32;

architecture dataflow of not_gate_32 is
begin
  z <= not x;
end dataflow;
